# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 09:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDirection', models.CharField(choices=[('out', 'KW'), ('in', 'KP')], default='out', max_length=3)),
                ('itemDate', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('title', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wpis utworzony przez+', to=settings.AUTH_USER_MODEL, verbose_name='Wpis utworzony przez')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(default=datetime.datetime(2016, 12, 1, 0, 0), verbose_name='Data od')),
                ('toDate', models.DateField(default=datetime.datetime(2016, 12, 31, 0, 0), verbose_name='Data do')),
                ('lastAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Przeniesienie')),
                ('trasnferAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stan kasy poprzedni')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kasa', to='main.Book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Utworzony przez+', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Waluta', to='main.Currency', verbose_name='Waluta raportu')),
            ],
            options={
                'get_latest_by': 'fromDate',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Raport', to='main.Report'),
        ),
    ]
