# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170316_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='lastAmount',
        ),
    ]
